[package]
name = "rfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"

[build-dependencies]
bindgen = "0.63.0"
pkg-config = "0.3.26"
